# Generated by Django 5.1.3 on 2024-11-23 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.TextField()),
                ('correo', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id_herramienta', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('En Uso', 'En Uso'), ('En Reparacion', 'En Reparacion')], max_length=15)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('rol', models.CharField(choices=[('Administrador', 'Administrador'), ('Tecnico', 'Tecnico')], max_length=15)),
                ('correo', models.EmailField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('duracion', models.IntegerField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmado', 'Confirmado'), ('Completado', 'Completado')], max_length=12)),
                ('descripcion', models.TextField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.cliente')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id_agenda', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('Programada', 'Programada'), ('Cancelada', 'Cancelada')], max_length=10)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Inventario', 'Inventario'), ('Servicios', 'Servicios')], max_length=10)),
                ('fecha_creacion', models.DateTimeField()),
                ('contenido', models.TextField()),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id_notificacion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Recordatorio', 'Recordatorio'), ('Alerta', 'Alerta')], max_length=12)),
                ('fecha_envio', models.DateTimeField()),
                ('contenido', models.TextField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Enviada', 'Enviada'), ('Fallida', 'Fallida')], max_length=9)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Egreso', 'Egreso')], max_length=7)),
                ('cantidad', models.IntegerField()),
                ('fecha', models.DateTimeField()),
                ('herramienta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.herramienta')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base_datos.usuario')),
            ],
        ),
    ]
